title: 周也的生活
description: Design & Code
# theme: jekyll-theme-architect  <-- 这行删掉或者注释掉，我们现在用的是自定义布局
markdown: kramdown
permalink: /:year/:month/:day/:title/
exclude: [README.md, Gemfile, Gemfile.lock]
